language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

os: 
  - linux

services:
  - docker

install: true

script:
  - go build ./...
  - docker-compose build schemaservice
  - docker-compose pull && docker-compose up -d && sh ./scripts/wait_for_fedora.sh
  - go test -v -tags=integration ./...
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh ./scripts/docker-push.sh'
