language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

os: 
  - linux

services:
  - docker

install: true

script:
  - go build ./...
  - go test -v ./...
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh ./scripts/docker-build.sh && sh ./scripts/docker-push.sh'
