language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

os: 
  - linux

services:
  - docker

install: true

script:
  - go build ./...
  - docker-compose build schemaservice
  - docker-compose pull fcrepo && docker-compose up -d && sh ./scripts/wait_for_docker.sh
  - go test -v -tags=integration ./...
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -z ${DOCKER_USERNAME+x} ]; then sh ./scripts/docker-push.sh fi'
